[theme]
base = "light"

# 🌅 Colors principals
primaryColor = "#ee5d6c"                # Rosa coral (accent)
backgroundColor = "#fff7f2"             # Fons principal
secondaryBackgroundColor = "#feece0"    # Sidebar / Cards
textColor = "#2b2b2b"                   # Text general
borderColor = "#f5c4c4"                 # Borde suau rosat

# 📊 Colors per gràfiques (categorical)
chartCategoricalColors = [
    "#eeaf61",
    "#fb9062",
    "#ee5d6c",
    "#ce4993"
]

# 🎨 Colors per seqüencials (gradients suaus sunset)
chartSequentialColors = [
    "#fff2eb",
    "#ffd7c9",
    "#ffbfa9",
    "#ff9c8a",
    "#ff796b",
    "#ee5d6c",
    "#d84c68",
    "#b83f66",
    "#96365a",
    "#732f4b"
]

# 💾 Taules i DataFrames
dataframeBorderColor = "#f5c4c4"
dataframeHeaderBackgroundColor = "#fbddd2"

# 🖋 Tipografies i forma
font = "sans-serif"
headingFont = "sans-serif"
baseRadius = "12px"
buttonRadius = "12px"
showWidgetBorder = true

# ───────────────────────────────────────────────
# Sidebar
[theme.sidebar]
backgroundColor = "#feece0"
textColor = "#2b2b2b"
primaryColor = "#ee5d6c"
